version: '3.7' # docker compose version, not python version

services:
  web:
    build: .
    command: python /wavenly/manage.py runserver 0.0.0.0:8000
    volumes:
        - .:/wavenly
    ports:
        - 8000:8000
    depends_on:
      - db
  db: 
    image: postgres:11
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"
volumes:
  postgres_data: